spring.application.name=SmartLead
server.servlet.context-path=/smart-lead
ai.huggingface.model=meta-llama/Llama-3.3-70B-Instruct


spring.datasource.url=jdbc:postgresql://localhost:5432/smart_lead
spring.datasource.username=stelanikolaeva
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
context-path