spring.application.name=SmartLead
server.servlet.context-path=/smart-lead
ai.huggingface.model=${AI_MODEL:dummy}
ai.huggingface.token=${AI_TOKEN:dummy}

spring.datasource.url=${DB_URL:dummy}
spring.datasource.username=${DB_USERNAME:dummy}
spring.datasource.password=${DB_PASSWORD:dummy}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver